Update Main.php
Infernus101/KitUI pull request #73
Opened 2018-03-03 01:15 UTC by BogdanMakarchuk

Validation on EconomyAPI

## KitUI Pull Request
- [ ] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ ] This PR description and comments in code is understandable in English.
- [ ] This PR has comments written in clear English.

## Pull Request description
...

## Optional information
...

2018-03-04 19:08 UTC, Infernus101 commented on src/Infernus101/KitUI/Main.php
> +            $this->getServer()->getPluginManager()->getPlugin("EconomyAPI");
else condition is not needed...

2018-03-05 05:05 UTC, DancingXXL requested changes

2018-03-05 05:05 UTC, DancingXXL commented on src/Infernus101/KitUI/Main.php
> +            $this->getServer()->getPluginManager()->disablePlugin($this);
You can just use
`$this->setEnabled(false);`
Also you may use _**return**_ to interrupt enabling

2018-03-05 05:11 UTC, DancingXXL commented on src/Infernus101/KitUI/Main.php
> +            $this->getServer()->getPluginManager()->disablePlugin($this);
Or not, _**disablePlugin()**_ would be better. My bad

2018-03-08 07:39 UTC, closed without merging